docs(cn): themes/write-a-theme translation
slidevjs/docs-cn pull request #18
Opened 2021-05-16 14:03 UTC by songhn233

- 我注意到 #14 中对于 Front Matter 的讨论，所以保留了原文，可以等确定后进行更改
- 原文中的 Capability 感觉直译比较奇怪，所以译为了 **自定义**，可以讨论是否有更合适的翻译

2021-05-16 16:11 UTC, antfu commented on themes/write-a-theme.md
> +## 注意事项 {#conventions}
```suggestion
## 约定 {#conventions}
```

2021-05-16 16:11 UTC, antfu commented on themes/write-a-theme.md
> +- web 字体
```suggestion
- 使用 Web 字体
```

2021-05-16 16:11 UTC, antfu commented on themes/write-a-theme.md
> +## 自定义 {#capability}
```suggestion
## 主题能力 {#capability}
```

2021-05-16 16:11 UTC, antfu commented on themes/write-a-theme.md
> +主题需要发布到 npm，所以需要遵守以下约定：
```suggestion
主题发布到 npm，需遵循以下约定：
```

2021-05-16 16:11 UTC, antfu commented on themes/write-a-theme.md
> +如果想要测试自己编写的主题，你可以新建 `example.md` 并在 frontmatter 中增加下行告知 Slidev 你不想使用现有的主题。
```suggestion
如果想要测试自己编写的主题，你可以新建 `example.md` 并在 frontmatter 中增加以下代码，以告知 Slidev 你不想继承于其他主题。
```

2021-05-16 16:11 UTC, antfu commented on themes/write-a-theme.md
> +主题可以定制的范围与自定义相一致，可以参阅 [自定义文档](/custom/)。
```suggestion
主题可以定制的范围与本地自定义相一致，可以参阅 [自定义文档](/custom/)。
```

2021-05-16 16:26 UTC, songhn233 commented on themes/write-a-theme.md
> +## 自定义 {#capability}
能力这词似乎不太常用，要不要译为 **主题功能** 或者 **主题特性**？

2021-05-16 16:58 UTC, QC-L commented on themes/write-a-theme.md
> +## 自定义 {#capability}
capability 本身就是能力的意思...主题能力没问题的。。。

2021-05-16 17:09 UTC, songhn233 commented on themes/write-a-theme.md
> +## 自定义 {#capability}
👌

2021-05-16 22:04 UTC, Ivocin requested changes
翻译的很好，一些建议请参考。

2021-05-16 22:04 UTC, Ivocin commented on themes/write-a-theme.md
> +在切换配色方案时 Slidev 会同时切换页面中的 `html` 元素是否含有 `dark` 类。
```suggestion
在切换配色方案时 Slidev 会将页面中的 `html` 元素切换为 `dark` 类。
```

2021-05-16 22:04 UTC, Ivocin commented on themes/write-a-theme.md
> +另外，不要忘记在 `package.json` 中指定支持的高亮工具：
```suggestion
另外，不要忘记在 `package.json` 中指定想要支持的高亮工具：
```

2021-05-16 23:37 UTC, songhn233 commented on themes/write-a-theme.md
> +在切换配色方案时 Slidev 会同时切换页面中的 `html` 元素是否含有 `dark` 类。
这里的意思应该是在切换为暗色模式时增加 `dark` 类，切换为亮色模式时移除 `dark` 类。所以直接改成切换为 `dark` 类感觉有歧义？

2021-05-17 01:12 UTC, antfu commented on themes/write-a-theme.md
> +在切换配色方案时 Slidev 会同时切换页面中的 `html` 元素是否含有 `dark` 类。
是的，原文比较贴近实际行为。我这边先合了，谢谢

2021-05-17 01:13 UTC, merged

2021-05-17 03:11 UTC, Ivocin commented on themes/write-a-theme.md
> +在切换配色方案时 Slidev 会同时切换页面中的 `html` 元素是否含有 `dark` 类。
> 这里的意思应该是在切换为暗色模式时增加 `dark` 类，切换为亮色模式时移除 `dark` 类。所以直接改成切换为 `dark` 类感觉有歧义？

在切换配色方案时 Slidev 会同时切换页面中的 `html` 元素是否含有 `dark` 类。

我的意思是，这句中文不太通顺，从汉语的角度读不太懂：”切换页面中的 html 元素是否含有 dark 类“ 这句，谓语 切换、宾语 html 元素，那“是否含有 dark 类” 这块不知道是什么结构，读不懂。 @songhn233 @antfu  你们读一下感觉一下呢？

2021-05-17 03:18 UTC, antfu commented on themes/write-a-theme.md
> +在切换配色方案时 Slidev 会同时切换页面中的 `html` 元素是否含有 `dark` 类。
`在切换配色方案时 Slidev 会同时切换页面 `html` 元素的 `dark` 类。`

2021-05-17 03:26 UTC, songhn233 commented on themes/write-a-theme.md
> +在切换配色方案时 Slidev 会同时切换页面中的 `html` 元素是否含有 `dark` 类。
在切换为暗色模式时 Slidev 会为页面中的 `html` 元素添加 `dark` 类？

2021-05-17 06:01 UTC, Ivocin commented on themes/write-a-theme.md
> +在切换配色方案时 Slidev 会同时切换页面中的 `html` 元素是否含有 `dark` 类。
赞，这样通顺多了