docs: add translations to 2 more files in /features
slidevjs/docs-cn pull request #230
Opened 2024-08-05 12:04 UTC by wemsx

- [ ] 我对翻译内容的改动不包含基于英文原版的扩展、删减或演绎 (如有，请移步至[主仓库](https://github.com/slidevjs/slidev))

**问题描述**:
较为不确定在 'features/direction-variant.md' 中的 navigating 的翻译，我标题直译的，在下面是写的“播放方向”
以及，我保留了 props
辛苦啦

2024-08-05 12:14 UTC, xiaodong2008 requested changes

2024-08-05 12:14 UTC, xiaodong2008 commented on features/direction-variant.md
> +你可能希望根据幻灯片反应方向来应用不同的类。 `.slidev-nav-go-forward` 或 `.slidev-nav-go-backward` 类将在放映时相应应用于幻灯片容器, 因而你可以用他们来实现不同的样式或动画：
应为滑动幻灯片的方向

2024-08-05 12:14 UTC, xiaodong2008 commented on features/direction-variant.md
> +/* 示例: 顺序时延迟，而在逆序时不生效 */
示例：向前切换幻灯片使延时，向后时不生效

2024-08-07 14:27 UTC, wemsx commented on features/direction-variant.md
> +你可能希望根据幻灯片反应方向来应用不同的类。 `.slidev-nav-go-forward` 或 `.slidev-nav-go-backward` 类将在放映时相应应用于幻灯片容器, 因而你可以用他们来实现不同的样式或动画：
谢谢🙏，马上改。

2024-08-08 03:42 UTC, KermanX approved these changes

2024-08-08 03:42 UTC, merged